#
# This file contains configuration flags to customize your site
#

# Site locale
lang: "en"

# Name of your site (displayed in the header)
title: Modern Millionaires Program Review

# Short bio or description (displayed in the header)
description: A comprehensive look into the Modern Millionaires

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANcAAADrCAMAAADNG/NRAAAAwFBMVEUAAADEpmLIqmXKrWfGqGPMr2nPs2y/oF2GbjzDpGC9nVrRtm62lFPbwXfQsmrZvXNIPiXhx3u8mVazkVGBbUCbh1K6nFtfUTBsWjTYvnWmik9kUi++m1fdxHkPDQh9aDwXFAwiHRE2LBlkWDZzZT5USi6Ne0u2n2EuJxeLcj4/NByCajofGQ6rl119bkQVEgvFrmuUfUlRQiWSgU+fjFZEPCXIsW4xKhmrj1NuYTumjlVYSSqdgEh1XzWjkFmOfU7NB2QaAAAXhElEQVR4nO2de1uqTBDAYbmJCAh5z3sqZmlZp5OZnvf7f6t3dmG5UyxK2fM0f5xDXvk5s7MzszeOK0/u5zebzaYdf3jj/HX+NTc382GJ312OTJrOo6aDdLtd3XyOPPd3gB/UBwPL0rvO+vnmm+6xiIwHpql1XTFNXXsNnlrrXWDymIHP+vd9t8kupqaZuv74uF6vTXz/Pthw0NWf2+1Fc/2oWZYFWvO1+Zr+URclj6a5efCuF6CZR/pEe9DV/FdN55vFvzn9S9f+uzi0Sbu9Cv/tmGbQbtoDTX/zrmd6d53+EXNLH1h/F5OybrGANEA9IP+Cn7tpmovg+X+mSRW20btaczGrTxMf8oc0Ost63FyIn5zK0JqwhFgWZtgLvuqa5V2uibPA3lB7XDc3oY+Bh/9awAZ+0kn0Dd8gL5jKfATLg//+eA/OTDNsbuBEXtwrB2N5nlIfPAYvATO0uOVCc9H+cN8tQ0z1jH3EDejNnLmPzgPLw6J1Kddjt/v8vAY6cIX6IMT+z/vr5RmjWbOvuftsaQIWdWkOXLtXdVOTQy8yNd1rUN3uwPUMYwhG/r0FL4GmRT1N/XEw+FvmPecRUzaD3xa4vCaja2bQ/G/A8rxL6L5S3cKNBSp89N58D66xlJv9TB78qxtTk4LHF6bmuFdgkoHHBnfpRRV1PdR9hQWHIV3whg7+kaCtdVNfVbbw/tVC05rB44H5PQbWCZ2Zpi/dy+mgm37HAEW8IfgMpwn/OvSJpZP6+lLkxfRZolwvPpejeR3zciZ3Nd3vALSu+XdxM1/GPnGGecFlDEhEDG3N7+Udi/syaWom/d4sfa3B9MDvgYM3ASuIbWdW18T33oVQvjm7qXsPO7pOXPt6gN2/NfB1fWNZ4U6uXJFlmVpiVvuCKxyCkN7abITeuxh0SSRsuv2zp41B13JR4LH1c4gEKL/MNd5osqxRJ5jhDzcuFyQpj7GQb/r8z83NdFBl173pN7/ZOfog3HU1LbDJZMxVjqxlCcDuvW/WZNO3JlCPd9k2nfVi87bKitCn9bcFJJ9dV70OJC/u43/0QciuVxbW6RcFHw8mYMna3v1rCMozF9jxtwVNM1njBNJj3Ftdy4tHNgM95AAfIfIAstPvOY80NJlvaxL143UTIN34UDaL/bTT9YDq+W2gB+1pAzHjfBAEItxmHn/riRJuIrysbThHlgV6VxImw20unJswCjXlldX11TPUccy4Hvid2cSy/o0Lf0WavJqCs2+OZvUVVwe1DLlXTdJ8ihnJv7T9ORo4mCT9EdcDHE61QWlefONYA2t8hu8IScOQZUM2cJolybhpLQAs6F0n7ZuX83wRBFOeseHMZeY+4jpZTPiW/c5iwksghoz/1Yi9C7JcRoiz+UtzFOgMSK7zTJtcdxBO2M4kL5okKTskgcLckGJuStrZfz0sdTdb/g8skhj2K6gJG8Mz/B+Pv84gTUMinmI197L0vSxLH73hNFkO/J4M0rGmi/f88XuKiew2LF+g5zrBAX4m/4JcBdy9Tvqy9BTnVHkzJC3Sf2zkMmvQm6DbAk3dvFm+Qzm3OJLERx54yHjheST4dHD4EGkNMgqPJwv0WXLj85edX+YWKS2W9vkLQzK+pR6L4/8y8zAkGV+YlgcCXZh+/q4rEAh3je+oxS69Lqw02RtSiX1WtjyWXAEea5rzVelrWGZlV282o5K/IF3GP2m09ld+5Vd+5Vd+pQRpP333HXwiN4XyzKkhXXYnv7H0AvNzHhAyLlthG6vIEFILGZ3z38tZ5T9rwJwNNgWpvFrTuWQ9YK28zQy0//xV3y5/BxaTD5gaSCnrXs4p44FusRRcFGR8R/bILnMm37FH0qX7DCrPltX8/FWuXEs/onG58jiwclaSxoLIf/6qS5FJ7jlHO9Gof/6qi5E3K1+Bu4PQtux7Oas4gzwDEkNR/BEuPpDhII8lNkXhJ1khFrDET6umdUH8WVaI5TE0/y1DWqJ4IdO8GeTV+mxUYobQT+mRw/I8+HgCxJAXW191L2cV/WPX0RDRT3Marsws67/sZyei2Pu6ezmr/P1oBvdWRBe3oientK1BZoq5RD/Qx1MBX5/lyEFdl7RKiU1AYRkJywSpP1ddRGHpT1R+srqyW9hQ5H+yurDCUl3iUUSfBVmXLRD+pk1dUdSf2ndR0dImvLVF8Z3lQ7ZfEh4/s4Q/i7Rq4k5liwx5qfwZDzeyxcI1tPREXXspqkem71SQpDApmFmmjqmZTOHqWrfi8VJDFNm+VUEiMvYlzLf1ZNgki3aYuOZJV6+w9snAJSJklDU4sdHI4mE2Loh+Y+nKkygyDnZhLiAThDLy0PkjXRLNxrXQY0XSrcpahHK5QGVS69wp28TxqJi5xpYerSWqKusEV58LjHF/1vjr2adi5oKYI7L46F0VWcdPPC5CJkjnm/Y7k0NYzFybwSBc6Ngydl5ciIuoTELnmUZa58NU7FyTqCEqzGbIKWKYC4xxd/qI2XBv4uVWJ3BFDbGuqswhryLyUTLB2J44n76BqeQIGDPXRh8EsdRIrTLfBHDFwMDnnxJa3QguVQSMmWtl6UFNe1cgUcZcAZhHJvFFl1qsHFMOCcVymD2tFizUH6oqe6RHuOIaQ0VDq6apyXIczJQKOKM/QYzYVlX2pAP8Bp9GJhQIrTZajMoFK9R5vA10ml3eqjv297fEDDDw+WzL3eZ8kkrWzD9j9pviyB4X1NPv1Ar7+1sEKBUMGa38ixOWaxMv845TOYWXNzz6O0YUaV7ARYjSwQRjf5/vY7agK7xmM4oln7DA0W9g70WaF+XCYAglwIAsT+t4k1wTjICdsgwaf6auuwtPR+xBFBfyhzxqLAyUAEOS+NnUpRdH84jCGjMzoui3nFO8pgOvBzsUKvMGfh41uNcdJQuBIePDpSz3e82QJEpEwTSU3gO+OnreeTV017SWWiQ1dLkwGcIW964ISTDBaGZaeMNdC03B3P80OWPxGi4K5OVyuqQ++qCqRRLDFu+JKLgtaSSgBBiSMqpWbRRQeZqC/8zn9J9hQ4KPvFzP+gA70ydVLYAVcPGIeoita4woSsYnne3UMaSokIblpA++0aJAXq6Z6zg6aq0Yl6rGuLhVS0qSCcYuGloNm3EqDKYJ6UHTZE0zsrxcdZ1sUlJRD8W4KBgKefQ2LyRVFg2tRpIhCAmsrIW2CwgcGbk4i+zCcmDPKT0uDwxF3t8gKouChUKrOW9IQpxL1prp3fibHMrIcnP9JSF9MXfoti8CFuXixnsDJcAEg1StJntCFQPTMoKmeih3YeFySCSlqIWmybdUCobi+q63gAwlyPaTBaUKk8kZyw8e/oRyF2yMubn+mfoSu/lCVbKWSsESXGA/SIhzIUEyDCEshMrISmsaiYwsN9eiq8+5OnNF1OdSCZeawkV8fpIsLmCCGWloGyVyl/xcJEJ8V9hrG4SLVz1/KKb6neUuSRbHMvj0JjCNFgVYudp6d8N1lGLDlISLkKVz4TxB+hDMMDI2m2qaspRIyRiKAq+6+Yc7lsaFQyshk0syMqLtmaYlEjLIXRg6o4luNrmKcsuKRKSlevIBFzdMNDOfap0e6895zZDjqaZm7plKk6bpAFeBIgAX4lI/4IKm0jJSwIyUoBHLZK0FeUuQkfGMRQENuLblcnHcNS/EwKSsXHqhyZH43uu6mIsCXfOR6ynXrG8jkpsLp1phssykrCP5uUuQaRYqCjhm9yu4IDU2AionPdt7cbRo3uIGjusiZVbH1M7LVW+10nOouuKSSSg9aBrvw1RUY7JwyFnWiorTPSvXfROSFCHDfePQKrMW3DCSKRmA7e5uC1XFiR1Wz8XVEEUS3osZoyrbrPHatpiSaEpaq3JXKc5VK8ylRLhWLUTiRUzWSg+P0t3FdJeSkUkyv72rVApzadxVcS4l4JocKy3VzzRFIf9I+jYtI5OlA6Y6hetQuH35XCPu+rZyRxMXr0iVzz3PpCAj86kMaFiVyolcxduXorhkYDG3FZ+Lp9Uc/vM0/EmJZGS0KLC7pVh320JTIk/j8sF65BZo4kLLVCL6ZMLKch/NM100w1ktbynWjnkc1uXqnsRFwJQIl18ccI0xu9yLN0UTEpmmZEgQNK1crruDIGvFuHD76heb4NQiqsJcfJzLB+ORkBWLdJCUzDQlt38jXHe3PIQcxbjw9siVasG41zVC/K/HRfOWMJgoqGnp4AuN8qNUXlEAuO4qLdKnFeTCeUr1rhiX5w8TXDEwUUhMWLlvhgLhIH325xKsKnd7ye2qi3ON+sVmlxN/SMDCXBByJMDEWGbciGbR1GEEUcrq4I9KFOKa4Lyy0y9Uxh4pCnWHAZcodo6YLA6GUFDJaPPxElyiKNAOYuCiXE3uul+gvtF2ey+PjPoNsmpnuBX4cA/tjmkKXmg13aUWg6Om2jZO45rjQ2nqfZv1fa87nyrEpdKbW+1QpCNzRzUl7BS2qcV7MeZaQlyFVoi3TXPGLftVtlHz4a2oRETtQXhwexeKda+9wcwwGI+MrSgkh6FT5i62DeEkrgU+9GnY7zPFYEdFVeJcgBWrwzSQmADj/WkDAZhgNMeJr2gHA0mFuJ5NvId8rc8w7vDUilNhrttk136/F+LeIzLXw8VKn8CCuYQT2teanLrT6+deEDDpqUo1yXVIVXi9hWIai8yAw8rKWFPscgmFuR7JaQy3/dwBR0etVlO4smYddlQxboohsuwJYm3Dj+8LcZkanuhwrObuwAhXgiyTC/t8MWGKnro+mNBHuYRiXK+mhs9ree/nHjfvKNUUsGwuPKoipLYxKaNUQMTnEgr5jRv3fLVlv5+3mEW5qrm58IQVxMc1hoQPj+0IuIQiXA3TJB1iP7dD9Lmq+bkg5PIaFgVD0icR6Ylc4A6Jiff6eacbB1xVBi5ujJvZB/F9XEJccgEuwTuc5i535BvYodpr5efCoyqCh4WUz4fnTtPXmJ6RdJ3bcVAutfXOMXHBl6i4N0Moz2tP42qb3gEo4DhyLlVwuVyQGhsXDq2QkBI0pd3ZSVwLzfRMopa3xEG4VHdZQ8uPPHJyccttzps8jcuhZxdy27wpM3CpO6+i11Ko98jLlVtO49LoEWRcx87ZwDpqyy/Klckl+WUPdq656Z8vlLuBdUKRZMt392VwFdfXInRg4ZXNtsYXS8vvyErRFyrKFTQvjqvY7DWOmt9Dl9C+gokDrFwPphYsbHvq95ln0Ptc1ZK4CBkz15umhWJP22YuZpfJRecfFeCC4HAc/HWwmYuIX8GF2LkCL4/l2u6zriH8Ei7EynUTMcMihhj4DZHdmX4s9aB8z8oVNUMIOZg9IuVSa+ffbfrVn7vIymXGzpB7t9mqiJRLUcrZpq7NS0W4Zlr8CLmazThcRLjUYnP88shIEti5HFmOPVLJGyNSAS61V+bmxQ94lIyNa2omJsuu+jbbOHNNaZW7XQoZ1WTjetbMRP24x+g5al9xoM8N216naSdPQhfGZFWFJpoxy5Blbj/EUCmz5WrsMceFCZ/wGlhGtv2Tt2eDjFLT0lb73dt2eV77K8SRtdSs5Nbu/2SFvZhy+gDNpF9CSPR1ciNnHUf6k6mwlHQc6a/8yq/8yq/8JPnZMVWWDHvMs9y+RRjL1NOrmv0DjkOY8YaUsewqVd7tWu0HxMBNPP6Xtfw0RY6A9QO4GgZewp7/xLZbjFW7+CRzDljO5D1vcxn3AOpw+VwTMEKyNe9wtlh8OC2JyOqqdmVvOfviuURBkHCJ+gYv9TM+W4x+bdeu8DzLXs2+7GxsJyBygnyHzJkVBO1DsDsbHDwudx4unGthILII+gWw0GIhCRL64NWHGljh1L26bC4DCfhIuTFYIxpz3IMkGNkKewJt9Vz/Ao7j6rZzsWcH3kiIHCnngBGSyvVeytocAsuxT6PCHmiuZtu1w/Eiz795kxDesrEp0UNRP+bi/KGH45VNejEM1yu2kKpMmRpIeoOOme47/gJ2mLdq8zQ6uGBXX1OKZ5KWgCS83s/daHOMBIHlqMMpxrqwqv1EwSv1x2RVkuRtzeOAuhgWmJLw1x0Oer+UdKyOEE9c2xb5J8sFzSyXjGhnhifk2IeLyFs6BhLjHmIEzYxhbd4BsGqup1+C4uxLOGlqa4jICA+TdradrUGbWR6ZYE/vdWZL7D4uIVzcCTziw78v+EEJvAef25ZI+EvbFM7GLuAonImKRGEXQdiRzLKVe67Qde3Kn5M4xD30k3v1nXRPeHOP+HB/p7lv5j9ZetW/uvLHjMAg+25/fbBzryA4v8wkUTTI18+KH23Ysa9obAixsDd3CnKYfrE192eQhcDzAvmpt1JCa/nlOPYubgHLVdKkX6t9Wy/WNniRJ66L+I6TnRhOyDwYXB849eMKy14UiS9f8th3nPxxR8A60MvvdIoKj3DDeEehjYGK7c2B5TrAWvWZZ4adU1o8Xos5wr6DRkx7qehJthiLTi4CZ/+dx55tRVVcbrHv8PLBpYJEqaD/gHD+auxeYvdR3tlR2dLZNoi1DVW8dEwVFS9nmkP4WxQLwHrex7zbRZYOnCwjFVAEYid1vMxKpB5jBH30Oc5Vu/LbWUiersrtza5borvfEXEUHTBC2iFvAQudYZbgO8TAyRisZ/dL7M+eMJWoVnqiKpAWsEW8u457uIOrjH3g2ORYqyVrHFPwkKU1uelOVBUV4W/dqaLrAnc8j09RflVEHu3Okg0e0yKNQy3FNs8jkx7C++dux/iPLU83fFN4le/g1bVZe9uxyhPYYTx0ebVrdkn99AMCXYkHN0LtiCryQvAlwluy8DxL0v+xXEHaEmunt+Woq4M9cEOlm1u/41bmx+8rsisJf76SZt0GsAjGxK7FSc8gFdV1Dap7cNeqhzXXClrxfaXZbJyz0PJ0hUv3oR/qLiX+WB5OJQVFkS5qpCoiN9kisufRR1sJnC4HrDI/QhxCDp3ovY79InsAhWUpKippVoCzE8m+TbznFkuTTg16555nEyMIsRKv6NXYl5HFZOedHNcBQPAdu/d6A5QmnqW3yhJSovL8/VUKwrhfCxa53D895ezcjpG6GVgeucDbYboLD5YtYESlRnGQZboXONJPPNuxfR12dn0Qu5Knsn9Qwj8A9YRtURHp4w3s33dlFvrqXo9VqaUsdzjUvNh4VevbeJDJrtKF7DHVKUroMNpqNfwTbVXv9J2dGpwHXVdUPtfOAqcKcCUNAxJq0uYhBa3Z/atev2rb3p5A172Ic25VFb/BTNVqeEf1J1AYuaiDwgL/u739kjL6McVtXHtmCM2s1h+N8SM1u6YQq7pWIsO6tari3/JRiS63qireORqgsNMLGYwyxpl0rLMCMyT++DYUYO1sm8wfu67a4e3Fw1wHso4scEK0C+NeQWFlr1hKCC7o2NH8y8O5B6/oD2GPwRLxH9f45oOWH+aCJ64AzA81lyp1GAdVKV4BLSpHsDogC1rZk+2W4a7tsIne2TZ2A6AvTEZ/hxDXCpoXXpOvjOlbaBfGTUSl2NEuJ8nyFpOB//B8+a2XywBJqG711LexVU37wGXb9GiCEBc0rwPoKOQUO76absWCewufJsM7ojPPmdHBidvIkuEJJJ8c4arVscpqxA/WqlVqd4eqMsJHXIScoh/MT76rvPxwpDTcyjNDrK9QTxPoy+bue6Az4vgPgUl6TeuoVv1DGbeKcqa88QQ5etnLHU2poX2F3PPIJunNtEr84gh8ev8w5LbVqqfTFTxCLrZKVfVYnyC6uIhBXyx+fI8tz3fPEPaTIRhsh/jvOl4dbE8DLmhenv3tAMxrdLvGd5QqU2XltiMsW7BIGk30bPdhyoVNEJpZzecCi6QuFW9UcgmDvVGZjmgjv8eD7OS2n64gtCK6m/Rtit0BMNumXODgqQd5BYW1xl93x8zy1Cezjw54JlLf8/nQWdPYfroDU/S4/OaF5f1wuRPNiKxqdG6VvxVmiAu6AoVyHav5N1+8BBlBpmL37WBX/AgX9171NuXuVdVvKPufIpP397BRRbm4+53bGq8q3zZgfR6JcZW/lvN/CF4DkXW2cyIAAAAASUVORK5CYII=

#
# Flags below are optional
#

# Your website URL (e.g. https://forever-jekyll.github.io or https://forever-jekyll.com)
# Used for Sitemap.xml and your RSS feed
url: https://modernmillionaires.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Navigation menu
navigation_links:
  - title: Blog
    url: /

  - title: About
    url: /about

  - title: Search
    url: /search

# Footer icons
footer_links:
  - title: Feed
    url: feed.xml
    icon: fa fa-rss-square

  - title: Twitter
    url: https://twitter.com/
    icon: fa fa-twitter-square

  - title: GitHub
    url: https://github.com/
    icon: fa fa-github-square

# Enter your copyright text if you wish to override the default one.
#copyright: "This site is made with <3 by *me, myself, and I*."

# Time zone
timezone: null

# Excerpt separator
excerpt_separator: <!--more-->

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: pretty

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - webrick
  - jekyll-github-metadata

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
